### PR TITLE
[ISSUE #6785] Isolate the remoteChannel by group

### LINKED ISSUE #6785: [Bug] The subscription data of Remoting may overlap in proxy
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

Ubuntu

### RocketMQ version

branch: develop

### JDK Version

OpenJDK 1.8

### Describe the Bug

For the order version client of remoting, the channel is shared between different pushConsumers. As a result, subscription data from different groups may overlap when receiving channel data from other proxies.

### Steps to Reproduce

Start two remoting pushConsumers with different groups with proxy

### What Did You Expect to See?

The subscription data is consistent with the subscription set in the client

### What Did You See Instead?

The subscription data is not consistent with the subscription set in the client

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xdkxlk**
### Which Issue(s) This PR Fixes

Fixes #6785

### CODE REVIEW

File: proxy/src/main/java/org/apache/rocketmq/proxy/service/sysmessage/HeartbeatSyncer.java [hunk 1]
```diff
@@ -49,7 +49,7 @@ public class HeartbeatSyncer extends AbstractSystemMessageSyncer {
 
     protected ThreadPoolExecutor threadPoolExecutor;
     protected ConsumerManager consumerManager;
-    protected final Map<String /* channelId as longText */, RemoteChannel> remoteChannelMap = new ConcurrentHashMap<>();
+    protected final Map<String /* group @ channelId as longText */, RemoteChannel> remoteChannelMap = new ConcurrentHashMap<>();
```
Comment (chenzlalvin) [inline proxy/src/main/java/org/apache/rocketmq/proxy/service/sysmessage/HeartbeatSyncer.java:52]: Will the "@" symbol conflict with the Group character?

Comment (xdkxlk) [reply proxy/src/main/java/org/apache/rocketmq/proxy/service/sysmessage/HeartbeatSyncer.java:52]: This is not a problem, as long as clients from different groups can be distinguished here.

**Review by lollipopjin — APPROVED** [review]
LGTM
