### PR TITLE
Fix start() and shutdown() of DefaultMessagingProcessor

### LINKED ISSUE #7837: [Bug] Receipt handle auto-renew scheduled task is not started
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

all

### RocketMQ version

develop

### JDK Version

_No response_

### Describe the Bug

The receipt handle auto-renew scheduled task is not started, resulting in duplicate consumption after handle expired.

image

### Steps to Reproduce

/

### What Did You Expect to See?

/

### What Did You See Instead?

/

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by redlsz**
### Which Issue(s) This PR Fixes

Fixes #7837 

### Brief Description

1. Complete ReceiptHandleProcessor's start() and shutdown()
2. Complete DefaultMessagingProcessor‘s start() and shutdown()

### How Did You Test This Change?

UT

### CODE REVIEW

File: proxy/src/main/java/org/apache/rocketmq/proxy/processor/DefaultMessagingProcessor.java [hunk 1]
```diff
@@ -124,6 +124,12 @@ public static DefaultMessagingProcessor createForClusterMode(RPCHook rpcHook) {
 
     protected void init() {
         this.appendStartAndShutdown(this.serviceManager);
+        this.appendStartAndShutdown(producerProcessor);
```
Comment (drpmma) [inline proxy/src/main/java/org/apache/rocketmq/proxy/processor/DefaultMessagingProcessor.java:127]: It seems that it's not necessary to start processors because this issue is only related to receiptHandleManager.

Comment (redlsz) [reply proxy/src/main/java/org/apache/rocketmq/proxy/processor/DefaultMessagingProcessor.java:127]: > It seems that it's not necessary to start processors because this issue is only related to receiptHandleManager.

Indeed, this issue is only related to receiptHandleProcessor. But all these processors extend AbstractStartAndShutdown and there is no caller, which may be error-prone over time?

**Comment by leizhiyuan** [comment]
any update?

**Review by yuz10 — APPROVED** [review]
