### PR TITLE
[ISSUE #6917] fix cannot query all messages of the same msgId

### LINKED ISSUE #6917: [Bug] cannot query all messages of the same msgId
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

Ubuntu 20.04

### RocketMQ version

5.1.1

### JDK Version

1.8.0_362-8u362-ga-0ubuntu1~22.04-b09

### Describe the Bug

cannot query all messages of the same msgId, using mqadmin queryMsgByUniqueKey

### Steps to Reproduce

1. create some retry messages using benchmark: `./consumer.sh -n localhost:9876 -g group1 -r 1`
2. query messages: `./mqadmin queryMsgByUniqueKey -n localhost:9876 -i <msgId> -t %RETRY%group1 -a true`
  "-a true" means show all messages.

### What Did You Expect to See?

show multiple messages

### What Did You See Instead?

only one message

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by yuz10**
### Which Issue(s) This PR Fixes

Fixes #6917

### CODE REVIEW

File: client/src/main/java/org/apache/rocketmq/client/impl/MQAdminImpl.java [hunk 1]
```diff
@@ -410,19 +410,7 @@ public void operationComplete(ResponseFuture responseFuture) {
...
                         if (isUniqKey) {
                             if (msgExt.getMsgId().equals(key)) {
-
-                                if (messageList.size() > 0) {
-
-                                    if (messageList.get(0).getStoreTimestamp() > msgExt.getStoreTimestamp()) {
-
-                                        messageList.clear();
-                                        messageList.add(msgExt);
-                                    }
```
Comment (RongtongJin) [inline client/src/main/java/org/apache/rocketmq/client/impl/MQAdminImpl.java:420]: If only one is to be kept, do we need to retain the original semantics and ensure that the storeTimestamp is the greatest for this one to be kept?

Comment (yuz10) [reply client/src/main/java/org/apache/rocketmq/client/impl/MQAdminImpl.java:420]: Actually, A consumer that achieves idempotence only takes the first message, and ignores others. So I think it's not appropriate to keep the last message.

**Review by RongtongJin — APPROVED** [review]
