### PR TITLE
[ISSUE #7523] message will flush timeout when transientStorePoolEnable=true and flushDiskType=SYNC_FLUSH

### LINKED ISSUE #7523: [Bug] message will flush timeout when transientStorePoolEnable=true and flushDiskType=SYNC_FLUSH
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

OS, window, linux

### RocketMQ version

5.1.5

### JDK Version

1.8

### Describe the Bug

image

1.set transientStorePoolEnable=true, flushDiskType=SYNC_FLUSH,
2.start broker
3.then send message to broker, client receives FLUSH_DISK_TIMEOUT error

By arthas, i find GroupCommitService always return FLUSH_DISK_TIMEOUT
image

### Steps to Reproduce

1.transientStorePoolEnable=true
  flushDiskType=SYNC_FLUSH

2.start broker

3.start to send message

4.client will receive FLUSH_DISK_TIMEOUT

### What Did You Expect to See?

no FLUSH_DISK_TIMEOUT received

### What Did You See Instead?

FLUSH_DISK_TIMEOUT received

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by fujian-zfj**
### Which Issue(s) This PR Fixes

Fixes #7523

### Brief Description

1.set transientStorePoolEnable=true, flushDiskType=SYNC_FLUSH,
2.start broker
3.then send message to broker, client receives FLUSH_DISK_TIMEOUT error

By arthas, i find GroupCommitService always return FLUSH_DISK_TIMEOUT

### CODE REVIEW

File: store/src/main/java/org/apache/rocketmq/store/CommitLog.java [hunk 1]
```diff
@@ -1634,12 +1634,18 @@ private void swapRequests() {
         private void doCommit() {
             if (!this.requestsRead.isEmpty()) {
                 for (GroupCommitRequest req : this.requestsRead) {
-                    // There may be a message in the next file, so a maximum of
-                    // two times the flush
-                    boolean flushOK = CommitLog.this.mappedFileQueue.getFlushedWhere() >= req.getNextOffset();
-                    for (int i = 0; i < 2 && !flushOK; i++) {
+                    boolean flushOK = false;
```
Comment (RongtongJin) [inline store/src/main/java/org/apache/rocketmq/store/CommitLog.java:1637]: How about flushOK=CommitLog.this.mappedFileQueue.getFlushedWhere() >= req.getNextOffset() when init？ Prevent every request from flushing at least once.

Comment (fujian-zfj) [reply store/src/main/java/org/apache/rocketmq/store/CommitLog.java]: OK

**Review by RongtongJin — APPROVED** [review]

**Review by joeCarf — APPROVED** [review]
