### PR TITLE
[ISSUE #1473] trace message`s clientHost was wrong

### LINKED ISSUE #1473: trace message`s clientHost was wrong
1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
When TraceDataEncoder encrypts/decrypts tracedata, there is no client information. The default data is used when decrypts tracedata, which is wrong.
image
image
- What did you expect to see?
The correct clientHost should be clientId

### PR DESCRIPTION
**Pull request by ChaosYjh**
## What is the purpose of the change

Fixes #1473 

## Brief changelog

add clientHost to trace message

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Review by RongtongJin — APPROVED** [review]

**Comment by gaoyf** [comment]
@RongtongJin  为啥要merge这个代码？之前#1473 都说过了，trace消息MessageExt的bornHost就是客户端ip，为啥还要把这个ip放到消息体里？
image

File: client/src/main/java/org/apache/rocketmq/client/trace/TraceDataEncoder.java [hunk 1]
```diff
@@ -62,6 +62,14 @@
                     bean.setOffsetMsgId(line[12]);
                     pubContext.setSuccess(Boolean.parseBoolean(line[13]));
```
Comment (readwall) [inline client/src/main/java/org/apache/rocketmq/client/trace/TraceDataEncoder.java:63]: wuqin
