### PR TITLE
[ISSUE #4522] Fix topic route info not found in some case

### LINKED ISSUE #4522: Broker's first registration may not take effect
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
   - restart namesrv .
   - 10s after namesrv starts, send a request to create a topic to one broker
- What is expected to see?
   - namesrv should has routes of all topic 
- What did you see instead?
   - Only the routing information of the topic just created

2. Please tell us about your environment:
- OS: linux
- branch: dev

4. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):
- When the client sends a request to create a topic, the broker will register the routing information of the newly created topic to namesrv
- But the broker may not have registered the all routing information to namesrv at the moment.
- The following code will treat the request of the first step as the first registration, so that the first full registration of the broker will not take effect.
https://github.com/apache/rocketmq/blob/cdfa5ced7e8152e0b359fdeeb2694be641eb5e29/namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager.java#L155
- The broker will not be able to complete the full registration until the TopicConfigManager's dataversion is changed.

### PR DESCRIPTION
**Pull request by cserwen**
**Make sure set the target branch to `develop`**

## What is the purpose of the change

Fix #4522 

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Review by hzh0425 — APPROVED** [review]

**Review by Kvicii — APPROVED** [review]

File: store/src/test/java/org/apache/rocketmq/store/dledger/DLedgerMultiPathTest.java [hunk 1]
```diff
@@ -46,8 +46,8 @@ public void multiDirsStorageTest() throws Exception {
             DefaultMessageStore dLedgerStore = createDLedgerMessageStore(base, group, "n0", peers, multiStorePath, null);
             Thread.sleep(2000);
             doPutMessages(dLedgerStore, topic, 0, 1000, 0);
-            Assert.assertEquals(11, dLedgerStore.getMaxPhyOffset()/dLedgerStore.getMessageStoreConfig().getMappedFileSizeCommitLog());
             Thread.sleep(500);
+            Assert.assertEquals(11, dLedgerStore.getMaxPhyOffset()/dLedgerStore.getMessageStoreConfig().getMappedFileSizeCommitLog());
```
Comment (tsunghanjacktsai) [inline store/src/test/java/org/apache/rocketmq/store/dledger/DLedgerMultiPathTest.java:50]: Nice change here. I guess this is something that causes our CI to fail sometimes. Hope it works. How about making this a separate PR so that we could maybe merge it faster?

**Review by tsunghanjacktsai — APPROVED** [review]

File: store/src/test/java/org/apache/rocketmq/store/dledger/DLedgerMultiPathTest.java (hunk 1 above)
Comment (cserwen) [reply store/src/test/java/org/apache/rocketmq/store/dledger/DLedgerMultiPathTest.java:50]: > Nice change here. I guess this is something that causes our CI to fail sometimes. Hope it works. How about making this a separate PR so that we could maybe merge it faster?

@tsunghanjacktsai  Good suggestion, I'll deal with it later.

**Review by humkum — APPROVED** [review]

File: namesrv/src/main/java/org/apache/rocketmq/namesrv/processor/DefaultRequestProcessor.java [hunk 2]
```diff
@@ -240,6 +240,13 @@ public RemotingCommand registerBrokerWithFilterServer(ChannelHandlerContext ctx,
             registerBrokerBody.getFilterServerList(),
             ctx.channel());
 
+        if (result == null) {
```
Comment (Oliverwqcwrw) [inline namesrv/src/main/java/org/apache/rocketmq/namesrv/processor/DefaultRequestProcessor.java:243]: The `result` seems can not null, it is initialized in first line, please correct me if I understand error

> public RegisterBrokerResult registerBroker(
            final String clusterName,
            final String brokerAddr,
            final String brokerName,
            final long brokerId,
            final String haServerAddr,
            final TopicConfigSerializeWrapper topicConfigWrapper,
            final List<String> filterServerList,
            final Channel channel) {
        RegisterBrokerResult result = new RegisterBrokerResult();
        try {
            try {
                this.lock.writeLock().lockInterruptibly();

**Review by Oliverwqcwrw — CHANGES_REQUESTED** [review]

File: namesrv/src/main/java/org/apache/rocketmq/namesrv/processor/DefaultRequestProcessor.java (hunk 2 above)
Comment (cserwen) [reply namesrv/src/main/java/org/apache/rocketmq/namesrv/processor/DefaultRequestProcessor.java:243]:
```java
if (topicConfigWrapper.getTopicConfigTable().size() == 1) {
    log.warn("Can't register topicConfigWrapper={} because broker={} has not registered.", topicConfigWrapper, brokerName);
    return null; 
}
```

`null` is returned directly. @Oliverwqcwrw

Comment (Oliverwqcwrw) [reply namesrv/src/main/java/org/apache/rocketmq/namesrv/processor/DefaultRequestProcessor.java:243]: ok, I didn't notice you added this piece of code, thanks for your reply

File: namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager.java [hunk 3]
```diff
@@ -156,6 +156,10 @@ public RegisterBrokerResult registerBroker(
 
                 BrokerData brokerData = this.brokerAddrTable.get(brokerName);
                 if (null == brokerData) {
+                    if (topicConfigWrapper.getTopicConfigTable().size() == 1) {
```
Comment (Oliverwqcwrw) [inline namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager.java:159]: I think it is better to judge Greater than or equal to 1, `topicConfigTable` maybe greater than 1 when batch send message

**Review by Oliverwqcwrw — CHANGES_REQUESTED** [review]

File: namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager.java (hunk 3 above)
Comment (cserwen) [reply namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager.java:159]: I think this has nothing to do with sending messages. This is just when a topic is created, the broker will register the topic's routing information with namesrv, and it will only be 1. When the broker is fully registered, the size must be greater than 1, because the number of system topics has exceeded 1, right?

Comment (cserwen) [reply namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager.java:159]: Besides, If the judgment is greater than or equal to 1, it will be impossible to distinguish the full registration of the Broker from the registration which the topic is created

Comment (Oliverwqcwrw) [reply namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager.java:159]: Are you primarily trying to solve the problem of not being able to create a topic before first registering the broker

Comment (cserwen) [reply namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager.java:159]: > Are you primarily trying to solve the problem of not being able to create a topic before first registering the broker

I describe the current problem in detail in the issue. If someone creates a topic before the broker first registers with a new namesrv, the broker's first registration will fail. The registration can only be completed when the data version of TopicConfigManager is changed.

Comment (Oliverwqcwrw) [reply namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager.java:159]: Ok, I get it , Thanks for your reply

**Review by HScarb — APPROVED** [review]

**Comment by cserwen** [comment]
@duhenglucky ping~

**Review by duhenglucky — APPROVED** [review]
