### PR TITLE
[ISSUE #7208] fix: when deleting topic  also delete its pop retry topic

### LINKED ISSUE #7208: [Bug] Pop retry topic was not deleted when topic was removed
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

Windows 10

### RocketMQ version

branch: develop

### JDK Version

JDK8

### Describe the Bug

Messages retry in pop mode will create a pop retry topic for this topic and consumer combination.
When the original topic was removed, the pop retry topic of the original topic wasn't deleted.

### Steps to Reproduce

1. create a topic
2. produce some messages on this topic
3. consume this topic using pop consumer, but not ack, wait for messages to revive
4. pop retry topic will be created 
5. delete the original topic

### What Did You Expect to See?

All pop retry topics of this topic will be deleted.

### What Did You See Instead?

Pop retry topics aren't deleted.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by HScarb**
### Which Issue(s) This PR Fixes

Fixes #7208 

### Brief Description

when deleting topic, search for its pop retry topic and delete them

### How Did You Test This Change?

unit test was added

### CODE REVIEW

File: common/src/main/java/org/apache/rocketmq/common/KeyBuilder.java [hunk 1]
```diff
@@ -31,6 +31,13 @@ public static String parseNormalTopic(String topic, String cid) {
         }
     }
 
+    public static boolean isPopRetryTopicOfTopic(String retryTopic, String topic) {
+        if (!retryTopic.startsWith(MixAll.RETRY_GROUP_TOPIC_PREFIX)) {
+            return false;
+        }
+        return retryTopic.endsWith("_" + topic);
```
Comment (xdkxlk) [inline common/src/main/java/org/apache/rocketmq/common/KeyBuilder.java:38]: If there is a group called GroupA subscribe a topic called TopicA, there will have a pop retry topic called %RETRY%GroupA_TopicA.
But If there is another group called GroupB subscribe a topic called Another_TopicA, there will have a pop retry topic called %RETRY%GroupB_Another_TopicA.
Therefore, when deleting TopicA, other pop retry topic will be deleted by mistake.

Comment (HScarb) [reply common/src/main/java/org/apache/rocketmq/common/KeyBuilder.java]: Indeed, I'll check the consumer group names before deleting pop retry topics.

**Review by joeCarf — COMMENTED** [review]
changes LGTM but there are ci failures :)

**Review by joeCarf — APPROVED** [review]
LGTM

**Review by humkum — APPROVED** [review]

File: broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java [hunk 2]
```diff
@@ -542,16 +543,28 @@ private synchronized RemotingCommand deleteTopic(ChannelHandlerContext ctx,
             }
         }
 
-        this.brokerController.getTopicConfigManager().deleteTopicConfig(requestHeader.getTopic());
-        this.brokerController.getTopicQueueMappingManager().delete(requestHeader.getTopic());
-        this.brokerController.getConsumerOffsetManager().cleanOffsetByTopic(requestHeader.getTopic());
-        this.brokerController.getPopInflightMessageCounter().clearInFlightMessageNumByTopicName(requestHeader.getTopic());
-        this.brokerController.getMessageStore().deleteTopics(Sets.newHashSet(requestHeader.getTopic()));
+        final Set<String> groups = this.brokerController.getConsumerOffsetManager().whichGroupByTopic(topic);
+        // delete pop retry topics first
```
Comment (xdkxlk) [inline broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java:547]: Because we already have the groups, I feel that it is better to check directly whether the pop retry topic exists in the TopicConfigManager, like
```java
for (String group : groups) {
    String popRetryTopic = KeyBuilder.buildPopRetryTopic(topic, group);
    if (brokerController.getTopicConfigManager().selectTopicConfig(popRetryTopic) != null) {
        deleteTopicInBroker(popRetryTopic);
    }
}
```

Comment (HScarb) [reply broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java:547]: ok, I’ve updated the code

File: broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java [hunk 3]
```diff
@@ -542,16 +543,29 @@ private synchronized RemotingCommand deleteTopic(ChannelHandlerContext ctx,
...
+        for (String group : groups) {
+            final String popRetryTopic = KeyBuilder.buildPopRetryTopic(topic, group);
+            if (brokerController.getTopicConfigManager().selectTopicConfig(popRetryTopic) != null) {
+                deleteTopicInBroker(popRetryTopic);
+            }
+        }
+        // delete topic
+        deleteTopicInBroker(requestHeader.getTopic());
```
Comment (joeCarf) [inline broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java:555]: deleteTopicInBroker(topic);

**Review by xdkxlk — APPROVED** [review]
LGTM

**Review by yuz10 — APPROVED** [review]
