### PR TITLE
[ISSUE #9501] correcting mismatched comments

### LINKED ISSUE #9501: [Doc] Correct interface parameter annotation errors
### Search before creation

- [x] I had searched in the [issues](https://github.com/apache/rocketmq/issues) and found no similar issues.

### Documentation Related

In the MappedFile interface, the `destroy()` and `shutdown()` method parameters are incorrectly annotated. They do not have boolean parameters.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by yx9o**
Fixes #9501 .

### CODE REVIEW

File: store/src/main/java/org/apache/rocketmq/store/logfile/MappedFile.java [hunk 1]
```diff
@@ -220,15 +220,15 @@ public interface MappedFile {
     /**
      * Destroys the file and delete it from the file system.
      *
-     * @param intervalForcibly If {@code true} then this method will destroy the file forcibly and ignore the reference
+     * @param intervalForcibly The time interval in milliseconds after which remaining references will be forcibly released during destroy
```
Comment (lizhimins) [inline store/src/main/java/org/apache/rocketmq/store/logfile/MappedFile.java:223]: after which any remaining references
