### PR TITLE
[ISSUE #6287] Fixed two redundant judgments

### LINKED ISSUE #6287: Fixed two redundant judgments
Fixed some redundant judgments in the GrpcConverter and GrpcServerBuilder classes

1.  class GrpcConverter
image

2. class GrpcServerBuilder
image

### PR DESCRIPTION
**Pull request by socutes**
close #6287

### CODE REVIEW

**Comment by socutes** [comment]
@xdkxlk PTAL

File: proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/common/GrpcConverter.java [hunk 1]
```diff
@@ -143,9 +143,8 @@ protected SystemProperties buildSystemProperties(MessageExt messageExt) {
         if (uniqKey == null) {
             uniqKey = messageExt.getMsgId();
         }
-        if (uniqKey != null) {
-            systemPropertiesBuilder.setMessageId(uniqKey);
-        }
+
+        systemPropertiesBuilder.setMessageId(uniqKey);
```
Comment (zhouxinyu) [inline proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/common/GrpcConverter.java:147]: It is also possible to return null for messageExt.getMsgId()?

**Review by drpmma — APPROVED** [review]
LGTM
