### PR TITLE
[ISSUE #8289] Fixed network bugs and merged networkutil code

### LINKED ISSUE #8289: [Bug]  networkutil code logical errors
### Before Creating the Bug Report

-  I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

linux

### RocketMQ version

develop

### JDK Version

jdk8

### Describe the Bug

1，TraceBean： private static final String LOCAL_ADDRESS = UtilAll.ipToIPv4Str(UtilAll.getIP()); getIP mayby ipv6
2，NetworkUtil：if (ip.startsWith("127.0") || ip.startsWith("192.168") || ip.startsWith("0."))；Check whether Intranet errors exist
3，0.0.0.0 到 0.255.255.255 通常不用于生产环境，因为它们可能与某些保留的地址或特殊用途的地址重叠。

### Steps to Reproduce

Read code logic

### What Did You Expect to See?

Read code logic

### What Did You See Instead?

No response

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by zekai-li**
Fix the following three as
1，TraceBean： private static final String LOCAL_ADDRESS = UtilAll.ipToIPv4Str(UtilAll.getIP()); getIP mayby ipv6
 2，NetworkUtil：if (ip.startsWith("127.0") || ip.startsWith("192.168") || ip.startsWith("0."))；Check whether Intranet errors exist

### Which Issue(s) This PR Fixes

Fixes #8289

### CODE REVIEW

File: client/src/main/java/org/apache/rocketmq/client/trace/TraceBean.java [hunk 1]
```diff
@@ -37,6 +37,15 @@ public class TraceBean {
     private String transactionId;
     private boolean fromTransactionCheck;
 
+    static {
+        byte[] ip = UtilAll.getIP();
+        if (UtilAll.isInternalIP(ip)) {
+            LOCAL_ADDRESS = UtilAll.ipToIPv4Str(ip);
+        } else {
+            LOCAL_ADDRESS = UtilAll.ipToIPv6Str(ip);
```
Comment (drpmma) [inline client/src/main/java/org/apache/rocketmq/client/trace/TraceBean.java:45]: Not being an internal IP does not necessarily mean it's an IPv6 IP.

Comment (zekai-li) [reply client/src/main/java/org/apache/rocketmq/client/trace/TraceBean.java:45]: Thanks, it has been modified

**Review by drpmma — APPROVED** [review]
LGTM

**Review by RongtongJin — APPROVED** [review]
