### PR TITLE
[ISSUE #5832] Fix consumerCount increasing rapidly without sending message

### LINKED ISSUE #5832: TodayConsumeCount is increasing rapidly without sending message
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

1. producer send little messages
2. stop producer
3. consume little messages after switch to mode POP
4. stop consumer
5. TodayConsumeCount is increasing rapidly  without sending message

image

- What is expected to see?

- What did you see instead?

2. Please tell us about your environment: develop

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

image

In DefaultMessageStore

this.storeStatsService.getGetMessageTransferredMsgCount().add(cqUnit.getBatchNum());

image

it is ok when in the mode PULL

### PR DESCRIPTION
**Pull request by Oliverwqcwrw**
**Make sure set the target branch to `develop`**

## What is the purpose of the change

Close #5832 

## Brief changelog

Fix consumerCount increasing rapidly without sending message

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

File: store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java [hunk 1]
```diff
@@ -849,7 +849,11 @@ public GetMessageResult getMessage(final String group, final String topic, final
                                 continue;
                             }
 
-                            this.storeStatsService.getGetMessageTransferredMsgCount().add(cqUnit.getBatchNum());
+                            if (topicConfig.isPresent()) {
+                                if (!topicConfig.get().getTopicName().contains(TopicValidator.RMQ_SYS_REVIVE_LOG)) {
```
Comment (ShadowySpirits) [inline store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java:853]: Store metrics should not exclude specified topics. It's better to add a new counter in BrokerStatsManager to calculate the message transfer count excluding all system topics.

**Review by ShadowySpirits — CHANGES_REQUESTED** [review]

File: store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java (hunk 1 above)
Comment (Oliverwqcwrw) [reply store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java:853]: IMO, It will broke the current structure of StoreStatsService if moving the getMessageTranferredMsgCount to BrokerStatsManager,

because not only is getMessageTransferredMsgCount in there but also other metrics is there,

whether moving the other metrics if moving getMessageTransferredMsgCount to BrokerStatsManager?

Comment (ShadowySpirits) [reply store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java]: I mean add a new counter in BrokerStatsManager and do not remove the current counter. The new counter only records the throughput of the user's topic. This is more general and semantically clear.

Comment (Oliverwqcwrw) [reply store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java]: Get it, I will polish it

File: store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java [hunk 2]
```diff
@@ -848,8 +848,8 @@ public GetMessageResult getMessage(final String group, final String topic, final
                                 selectResult.release();
                                 continue;
                             }
-
                             this.storeStatsService.getGetMessageTransferredMsgCount().add(cqUnit.getBatchNum());
+                            this.brokerStatsManager.incBrokerGetNumsWithoutSystemTopic(topic, cqUnit.getBatchNum());
```
Comment (ShadowySpirits) [inline store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java:852]: Using brokerStatsManager in the store module looks weird... It's better to add this counter in BrokerStatsManager#incBrokerGetNums.

File: store/src/main/java/org/apache/rocketmq/store/stats/BrokerStats.java [hunk 3]
```diff
@@ -88,6 +88,6 @@ public long getMsgPutTotalTodayNow() {
     }
 
     public long getMsgGetTotalTodayNow() {
```
Comment (ShadowySpirits) [inline store/src/main/java/org/apache/rocketmq/store/stats/BrokerStats.java:90]: How about dealing with getMsgGetTotalYesterdayMorning in the same way?

**Review by ShadowySpirits — CHANGES_REQUESTED** [review]

File: store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java (hunk 2 above)
Comment (Oliverwqcwrw) [reply store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java]: done

File: store/src/main/java/org/apache/rocketmq/store/stats/BrokerStats.java (hunk 3 above)
Comment (Oliverwqcwrw) [reply store/src/main/java/org/apache/rocketmq/store/stats/BrokerStats.java:90]: The getMsgGetTotalYesterdayMorning's data is from getGetMessageTransferredMsgCount,
so it's ok to replace the getGetMessageTransferredMsgCount to getNumsWithoutSystemTopic without adding other  counter

**Review by ShadowySpirits — APPROVED** [review]

**Review by mxsm — APPROVED** [review]

**Review by panzhi33 — APPROVED** [review]
