### PR TITLE
[ISSUE #8895] Fix NPE when broker shutdown and optimize the log

### LINKED ISSUE #8895: [Enhancement] CreateFlushConsumeQueueService for loadAndStartConsumerServiceOnly
### Search before creation

- [X] I had searched in the [issues](https://github.com/apache/rocketmq/issues) and found no similar issues.

### Documentation Related
loadAndStartConsumerServiceOnly need more service to support kvCq double write

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by qianye1001**
### Which Issue(s) This PR Fixes

Fixes #8895

### CODE REVIEW

File: common/src/main/java/org/apache/rocketmq/common/config/AbstractRocksDBStorage.java [hunk 1]
```diff
@@ -381,6 +381,7 @@ public synchronized boolean start() {
     public synchronized boolean shutdown() {
         try {
             if (!this.loaded) {
+                LOGGER.info("shutdown OK. {} is not loaded", this.dbPath);
```
Comment (lizhimins) [inline common/src/main/java/org/apache/rocketmq/common/config/AbstractRocksDBStorage.java:384]: The log content should be more specific

**Review by lollipopjin — APPROVED** [review]
LGTM
