### PR TITLE
[ISSUE #7689] In Controller mode, messages may lost due to sharing the same cq offset

### LINKED ISSUE #7689: [Bug] In Controller mode, messages may be lost due to sharing the same cq offset
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

During my testing of the controller mode, I encountered a scenario that could lead to message loss:

1. The leader controller and master broker are killed simultaneously.
2. Both are restarted at the same time, with the master broker completing recovery and immediately having messages written to it.

### RocketMQ version

5.1.4

### JDK Version

_No response_

### Describe the Bug

Since the master only recovers up to the position of the confirmOffset upon recovery, there may still be some messages that have not been synchronized by the slave. As a result, the data in the cqOffsetTable might be inaccurate. At this time, newly written messages could share the CQ offset with messages after the confirmOffset—this could lead to message loss.

### Steps to Reproduce

using openchaos, major-kill.
Killing brokers and controllers in the same time.

### What Did You Expect to See?

no message lost.

### What Did You See Instead?

message lost.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by GenerousMan**
### Which Issue(s) This PR Fixes

Fixes #7689 

Upon restart, it is necessary to compensate for messages after the confirmOffset by moving the cq offset backwards. It must be ensured that these messages remain unconsumable before the confirmOffset is reached.

### CODE REVIEW

**Review by RongtongJin — APPROVED** [review]

**Comment by RongtongJin** [comment]
LGTM～

File: store/src/main/java/org/apache/rocketmq/store/queue/ConsumeQueueStore.java [hunk 1]
```diff
@@ -444,6 +444,7 @@ public void recoverOffsetTable(long minPhyOffset) {
                 String key = logic.getTopic() + "-" + logic.getQueueId();
 
                 long maxOffsetInQueue = logic.getMaxOffsetInQueue();
+                log.info("Recover offset table, key: {}, maxOffsetInQueue:{}", key, maxOffsetInQueue);
```
Comment (RongtongJin) [inline store/src/main/java/org/apache/rocketmq/store/queue/ConsumeQueueStore.java:447]: 这个日志去掉吧，万一队列太多了打印很多，而且也不是最终的位点

**Review by RongtongJin — APPROVED** [review]
