### PR TITLE
[ISSUE #9213] Fix get the earliest time error when data is clean up in tiered storage

### LINKED ISSUE #9213: [Bug] Fix get the earliest time error when data is clean up in tiered storage
### Before Creating the Bug Report

- [x] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [x] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [x] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

[Bug] Fix get earliest time error when data is clean up in tiered storage

### RocketMQ version

before develop 5.3.2-SNAPSHOT

### JDK Version

JDK11

### Describe the Bug

Get earliest time error when data is clean up in tiered storage

### Steps to Reproduce

Get earliest time error when data is clean up in tiered storage

Image

### What Did You Expect to See?

No error

### What Did You See Instead?

Get earliest time success

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by lizhimins**
### Which Issue(s) This PR Fixes

Fixes #9213

### CODE REVIEW

**Review by lollipopjin — DISMISSED** [review]
LGTM

File: tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/FlatMessageFile.java [hunk 1]
```diff
@@ -178,16 +178,20 @@ public AppendResult appendConsumeQueue(DispatchRequest request) {
...
 
-
-
     @Override
     public void release() {
-
     }
 
     @Override
     public long getMinStoreTimestamp() {
```
Comment (lollipopjin) [inline tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/FlatMessageFile.java:186]: Add some java doc here, for using min timestamp in metadata instead of read commitLog from tiered stortge.

Comment (lizhimins) [reply tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/FlatMessageFile.java:186]: already add to TieredMessageStore#getEarliestMessageTimeAsync

**Review by lollipopjin — APPROVED** [review]
LGTM
