### PR TITLE
[ISSUE #5663] Fix Messages may be lost when SyncStateSet expand in extreme scenarios

### LINKED ISSUE #5663: Messages may be lost when SyncStateSet expand in extreme scenarios
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

当前 SyncStateSet 变更的时候，由Master Broker上报并且Controller成功应用后才会应用到本地，这保证了SyncStateSet收缩时不会有消息丢失。但是这无法保证SyncStateSet扩张时数据的一致性，举一个例子

A为Master，B为Slave，一开始SyncStatetSet为{A}，当B追上A时（slaveAckOffset > confirmOffset）, SyncStateSet将从{A}变成{A,B}，按照当前实现的逻辑，首先{A,B}要上报Controller成功应用后才会应用到本地，因此在上报Controller到Controller确认应用成功这段时间内，SyncStateSet仍然为{A}，此时发送过来的消息只需要A确认即可返回成功，假设Controller成功应用上报的信息SyncStateSet为{A，B}，但返回给A确认丢失，此时A下线，由于Controller中SyncStateSet为{A,B}，B被选为主，那么就可能会出现消息丢失。

image

- What is expected to see?

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

### PR DESCRIPTION
**Pull request by hzh0425**
… missing messages

**Make sure set the target branch to `develop`**

## What is the purpose of the change

Close #5663 

## Brief changelog

Add a new state 'isSynchronizingSyncStateSet'  in 'AutoSwitchHAService' to Solve the problem of missing messages

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

File: store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java [hunk 1]
```diff
@@ -88,10 +92,11 @@ public void shutdown() {
     @Override
     public void removeConnection(HAConnection conn) {
         if (!defaultMessageStore.isShutdown()) {
-            final Set<String> syncStateSet = getSyncStateSet();
+            final Set<String> syncStateSet = new HashSet<>(this.syncStateSet);
```
Comment (mxsm) [inline store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java:95]: new HashSet should set capacity, to avoid invoke resize method.

File: store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java [hunk 2]
```diff
@@ -258,12 +269,38 @@ public void maybeExpandInSyncStateSet(final String slaveAddress, final long slav
...
+
+    private void markSynchronizingSyncStateSetDone() {
+        this.writeLock.lock();
+        try {
+            this.isSynchronizingSyncStateSet = false;
+            this.remoteSyncStateSet.clear();
+        } finally {
+            this.writeLock.unlock();
+        }
+    }
```
Comment (mxsm) [inline store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java:298]: lock not must. this method is invoked by setSyncStateSet method that has write lock
```
    public void setSyncStateSet(final Set<String> syncStateSet) {
        this.writeLock.lock();
        try {
            markSynchronizingSyncStateSetDone();
            this.syncStateSet.clear();
            this.syncStateSet.addAll(syncStateSet);
            this.confirmOffset = computeConfirmOffset();
        } finally {
            this.writeLock.unlock();
        }
    }
```

File: store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java [hunk 3]
```diff
@@ -356,26 +402,44 @@ private long computeConfirmOffset() {
...
+        this.readLock.lock();
+        try {
+            if (this.isSynchronizingSyncStateSet) {
+                Set<String> unionSyncStateSet = new HashSet<>(this.syncStateSet.size() + this.remoteSyncStateSet.size());
+                unionSyncStateSet.addAll(this.syncStateSet);
+                unionSyncStateSet.addAll(this.remoteSyncStateSet);
+                return unionSyncStateSet;
+            } else {
+                return new HashSet<>(this.syncStateSet);
+            }
```
Comment (mxsm) [inline store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java:429]: setting Hashset size

File: store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java [hunk 4]
```diff
@@ -258,12 +269,38 @@ public void maybeExpandInSyncStateSet(final String slaveAddress, final long slav
...
+            this.isSynchronizingSyncStateSet = true;
+            this.remoteSyncStateSet.clear();
+            this.remoteSyncStateSet.addAll(newSyncStateSet);
+        } finally {
+            this.writeLock.unlock();
+        }
+    }
+
+    private void markSynchronizingSyncStateSetDone() {
+        this.writeLock.lock();
```
Comment (RongtongJin) [inline store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java]: setSyncStateSet已经有lock了，这里不需要再lock

File: store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java [hunk 5]
```diff
@@ -258,12 +269,38 @@ public void maybeExpandInSyncStateSet(final String slaveAddress, final long slav
...
+        try {
+            this.isSynchronizingSyncStateSet = false;
+            this.remoteSyncStateSet.clear();
```
Comment (RongtongJin) [inline store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java]: 是否有必要remoteSyncStateSet.clear()，一个是markSynchronizingSyncStateSet执行时会调用remoteSyncStateSet.clear()，另一方面平时remoteSyncStateSet为空也不符合语义

Comment (hzh0425) [reply store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java]: Good idea

**Comment by hzh0425** [comment]
@RongtongJin PTLA

**Comment by RongtongJin** [comment]
Hi @hzh0425 Could you help reslove the conflct?

**Review by TheR1sing3un — APPROVED** [review]
LGTM~

**Review by RongtongJin — APPROVED** [review]
