### PR TITLE
[ISSUE #7851] Fix hashcode and equals methods of SubscriptionGroupConfig

### LINKED ISSUE #7851: [Bug]SubscriptionGroupConfig has bug when compare
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

any

### RocketMQ version

5.x

### JDK Version

_No response_

### Describe the Bug

Missing comparison of consumeMessageOrderly.

```
 @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + (int) (brokerId ^ (brokerId >>> 32));
        result = prime * result + (consumeBroadcastEnable ? 1231 : 1237);
        result = prime * result + (consumeEnable ? 1231 : 1237);
        result = prime * result + (consumeFromMinEnable ? 1231 : 1237);
        result = prime * result + (notifyConsumerIdsChangedEnable ? 1231 : 1237);
        result = prime * result + ((groupName == null) ? 0 : groupName.hashCode());
        result = prime * result + retryMaxTimes;
        result = prime * result + retryQueueNums;
        result =
            prime * result + (int) (whichBrokerWhenConsumeSlowly ^ (whichBrokerWhenConsumeSlowly >>> 32));
        result = prime * result + groupSysFlag;
        result = prime * result + consumeTimeoutMinute;
        result = prime * result + subscriptionDataSet.hashCode();
        result = prime * result + attributes.hashCode();
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        SubscriptionGroupConfig other = (SubscriptionGroupConfig) obj;
        return new EqualsBuilder()
            .append(groupName, other.groupName)
            .append(consumeEnable, other.consumeEnable)
            .append(consumeFromMinEnable, other.consumeFromMinEnable)
            .append(consumeBroadcastEnable, other.consumeBroadcastEnable)
            .append(retryQueueNums, other.retryQueueNums)
            .append(retryMaxTimes, other.retryMaxTimes)
            .append(whichBrokerWhenConsumeSlowly, other.whichBrokerWhenConsumeSlowly)
            .append(notifyConsumerIdsChangedEnable, other.notifyConsumerIdsChangedEnable)
            .append(groupSysFlag, other.groupSysFlag)
            .append(consumeTimeoutMinute, other.consumeTimeoutMinute)
            .append(subscriptionDataSet, other.subscriptionDataSet)
            .append(attributes, other.attributes)
            .isEquals();
    }
```

hashCode and equals lost info

### Steps to Reproduce

Missing comparison of consumeMessageOrderly.

### What Did You Expect to See?

add Missing comparison of consumeMessageOrderly.

### What Did You See Instead?

Missing comparison of consumeMessageOrderly.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by glcrazier**
### Which Issue(s) This PR Fixes

Fixes #7851 

### Brief Description

The `SubscriptionGroupConfig`'s equals and hashCode methods doesn't count `consumeMessageOrderly` field in.

### CODE REVIEW

File: remoting/src/main/java/org/apache/rocketmq/remoting/protocol/subscription/SubscriptionGroupConfig.java [hunk 1]
```diff
@@ -208,6 +209,7 @@ public boolean equals(Object obj) {
             .append(consumeEnable, other.consumeEnable)
             .append(consumeFromMinEnable, other.consumeFromMinEnable)
             .append(consumeBroadcastEnable, other.consumeBroadcastEnable)
+                .append(consumeMessageOrderly, other.consumeMessageOrderly)
```
Comment (leizhiyuan) [inline remoting/src/main/java/org/apache/rocketmq/remoting/protocol/subscription/SubscriptionGroupConfig.java:212]: wrong indent

**Review by leizhiyuan — APPROVED** [review]
LGTM

**Review by RongtongJin — APPROVED** [review]

**Review by mxsm — APPROVED** [review]

**Review by yuz10 — APPROVED** [review]

**Review by panzhi33 — APPROVED** [review]

**Review by joeCarf — APPROVED** [review]
