### PR TITLE
[ISSUE #6800] fix: change the config variable isEnableBatchPush to enableBatchPush 

### LINKED ISSUE #6800: [Bug] isEnableBatchPush can not be changed since the setter name is wrong
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

Linux

### RocketMQ version

4.9.x 

### JDK Version

_No response_

### Describe the Bug

isEnableBatchPush can not be changed since the setter name is wrong

### Steps to Reproduce

1. add `isEnableBatchPush=true` in the broker.properties config
2. use `enableDLegerCommitLog=true`
3. saw batch push is not enabled in dledger mode and the var isEnableBatchPush in MessageStoreConfig  still false

using test to reproducer
```Java
@Test
    public void testBrokerControllerConfigInit() throws Exception {
        Properties properties = new Properties();
        properties.setProperty("isEnableBatchPush", "true");
        MessageStoreConfig messageStoreConfig = new MessageStoreConfig();
        MixAll.properties2Object(properties, messageStoreConfig);
        assertThat(messageStoreConfig.isEnableBatchPush()).isTrue();
    }

```

### What Did You Expect to See?

isEnableBatchPush should be changed after set  `isEnableBatchPush=true` in the broker.properties config

### What Did You See Instead?

isEnableBatchPush did not change in the MessageStoreConfig

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by absolute8511**
Change-Id: I1ebf4748c26c42efb058c11a8b5084b69213892c

### Which Issue(s) This PR Fixes

Fixes #6800

### CODE REVIEW

File: store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java [hunk 1]
```diff
@@ -1129,7 +1129,7 @@ public boolean isEnableBatchPush() {
         return isEnableBatchPush;
     }
 
-    public void setEnableBatchPush(boolean enableBatchPush) {
+    public void setIsEnableBatchPush(boolean enableBatchPush) {
         isEnableBatchPush = enableBatchPush;
```
Comment (ferrirW) [inline store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java:1133]: IMO，change the isEnableBatchPush to enableBatchPush is better

Comment (absolute8511) [reply store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java:1133]: If change the var name I think it will break the compatibility.

Comment (cserwen) [reply store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java:1133]: Now we can set it in broker.cfg by `enableBatchPush`, so use `enableBatchPush` directly is better. @absolute8511

Comment (absolute8511) [reply store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java]: @cserwen since old isEnableBatchPush is ignored, and I think we can change the variable name `isEnableBatchPush` to `enableBatchPush`  without break compatibility.

**Review by cserwen — APPROVED** [review]

**Review by DongyuanPan — APPROVED** [review]
LGTM

**Review by RongtongJin — APPROVED** [review]
