### PR TITLE
[ISSUE #5847] Fix wake up in NotificationProcessor

### LINKED ISSUE #5847: Fix wake up in NotificationProcessor
Fix wake up in NotificationProcessor

### PR DESCRIPTION
**Pull request by drpmma**
## What is the purpose of the change

close #5847

## Brief changelog

Fix wake up in NotificationProcessor

### CODE REVIEW

File: broker/src/main/java/org/apache/rocketmq/broker/processor/NotificationProcessor.java [hunk 1]
```diff
@@ -244,6 +250,20 @@ private RemotingCommand processRequest(final Channel channel, RemotingCommand re
             int queueId = requestHeader.getQueueId();
             hasMsg = hasMsgFromQueue(false, requestHeader, queueId);
         }
+        // if it has message, fetch retry again
```
Comment (lizhimins) [inline broker/src/main/java/org/apache/rocketmq/broker/processor/NotificationProcessor.java:253]: not has message?

**Review by lizhimins — CHANGES_REQUESTED** [review]

**Review by caigy — COMMENTED** [review]
Could you provide more explanation about the change?

**Review by lizhimins — APPROVED** [review]
