### PR TITLE
[ISSUE 8230]fix the acl for NotifyClientTerminationRequest because group can be null

### LINKED ISSUE #8230: [Bug] fix the acl for NotifyClientTerminationRequest because group can be null.
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

Linux

### RocketMQ version

develop

### JDK Version

JDK11

### Describe the Bug

for NotifyClientTerminationRequest api, when notify the client of producer, the group can not be set. so the group will be null. when check the authorization of this request, the request will be failed if it is not set.

### Steps to Reproduce

use rocketmq-client-java to produce messages , and restart the client.

### What Did You Expect to See?

it will be passed when the producer send NotifyClientTerminationRequest with out set group in authorization logic.

### What Did You See Instead?

No

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by dingshuangxi888**
…ull.

### Which Issue(s) This PR Fixes

Fixes #8230

### CODE REVIEW

**Review by drpmma — APPROVED** [review]
LGTM

File: acl/src/main/java/org/apache/rocketmq/acl/plain/PlainAccessResource.java [hunk 1]
```diff
@@ -268,7 +269,9 @@ public static PlainAccessResource parse(GeneratedMessageV3 messageV3, Authentica
                 }
             } else if (NotifyClientTerminationRequest.getDescriptor().getFullName().equals(rpcFullName)) {
                 NotifyClientTerminationRequest request = (NotifyClientTerminationRequest) messageV3;
-                accessResource.addGroupResourceAndPerm(request.getGroup(), Permission.SUB);
+                if (StringUtils.isNotBlank(request.getGroup().getName())) {
```
Comment (yx9o) [inline acl/src/main/java/org/apache/rocketmq/acl/plain/PlainAccessResource.java:272]: Can you consider replacing `StringUtils.isNotBlank` with `org.apache.rocketmq.common.UtilAll#isBlank`.

Comment (dingshuangxi888) [reply acl/src/main/java/org/apache/rocketmq/acl/plain/PlainAccessResource.java:272]: It is the same. the UtilAll#isBlank is using StringUtils.isNotBlank

**Review by lizhimins — APPROVED** [review]
