### PR TITLE
[ISSUE #7534] use high performance concurrent set to replace copyonwriteset

### LINKED ISSUE #7534: [Bug] class Topiclist use CopyOnWriteArraySet will cause timeout
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

centos

### RocketMQ version

release 5.1.3

### JDK Version

jdk8

### Describe the Bug

when topic list in namesrv is huge(eg:50000), the interface getAllTopicList in routeinfomanager will cost a lot time,which may be timeout.

### Steps to Reproduce

use tools to call this interface, and calculate the time

### What Did You Expect to See?

topiclist on namesrv

### What Did You See Instead?

timeout

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by keranbingaa**
fix #7534

### CODE REVIEW

File: namesrv/src/test/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManagerNewTest.java [hunk 1]
```diff
@@ -131,6 +134,25 @@ public void getAllTopicList() {
         assertThat(topicList.getTopicList()).contains("TestTopic", "TestTopic1", "TestTopic2");
     }
 
+    @Test
+    public void hugeTopicListAddTest() {
+        Set<String> mapSet = ConcurrentHashMap.newKeySet();
+        Set<String> copyOnWriteArraySet = new CopyOnWriteArraySet<>();
+        HashSet<String> topics= new HashSet<>();
+
+        for(int i=0; i< 100000 ; ++i) {
```
Comment (joeCarf) [inline namesrv/src/test/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManagerNewTest.java:143]: seems that this line need to be reformatted

File: namesrv/src/test/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManagerNewTest.java [hunk 2]
```diff
@@ -131,6 +134,25 @@ public void getAllTopicList() {
...
+        }
+        long startTime = System.currentTimeMillis();
+        mapSet.addAll(topics);
+        long endTime = System.currentTimeMillis();
+        assertThat(endTime - startTime < 100).isTrue();
+        startTime = System.currentTimeMillis();
+        copyOnWriteArraySet.addAll(topics);
+        endTime = System.currentTimeMillis();
+        assertThat(endTime - startTime > 3000).isTrue();
+    }
```
Comment (RongtongJin) [inline namesrv/src/test/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManagerNewTest.java:154]: It seems that this test is unnecessary

**Review by RongtongJin — APPROVED** [review]
