### PR TITLE
[ISSUE #9069] Fix the IndexFile ConcurrentModificationException in tiered storage

### LINKED ISSUE #9069: [Bug] tiered store  ConstructIndexFile ConcurrentModificationException
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [x] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

linux

### RocketMQ version

devlop|5.3.x

### JDK Version

jdk1.8

### Describe the Bug

    public CompletableFuture<Void> commitAsync(FlatFileInterface flatFile) {
        return flatFile.commitAsync().thenAcceptAsync(success -> {
            if (success) {
                if (storeConfig.isMessageIndexEnable()) {
                    flatFile.getDispatchRequestList().forEach(
                        request -> constructIndexFile(flatFile.getTopicId(), request));
                }
                flatFile.release();
            }
        }, storeExecutor.bufferCommitExecutor);
    }
-------------------------------------------
I found this issue while conducting stress testing on tieredstore. When the TPS reached 100000, the Messenger Dispatcher # ConstructIndexFile call threw an exception
”java.util. ConcurrentModificationException“

### Steps to Reproduce

Tested again, it still appears, as shown in the screenshot below

### What Did You Expect to See?

Index construction without errors

### What Did You See Instead?

--

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by wangshaojie4039**
### Which Issue(s) This PR Fixes

Fixes #9069

### CODE REVIEW

File: tieredstore/src/main/java/org/apache/rocketmq/tieredstore/core/MessageStoreDispatcherImpl.java [hunk 1]
```diff
@@ -153,10 +160,22 @@ public CompletableFuture<Boolean> doScheduleDispatch(FlatFileInterface flatFile,
 
             // If the previous commit fails, attempt to trigger a commit directly.
             if (commitOffset < currentOffset) {
-                this.commitAsync(flatFile);
+                this.commitAsync(flatFile).whenComplete((result, throwable) -> {
+                    if (throwable != null) {
+                        log.error("topic: {}, queueId: {} flat file flush cache failed more than twice.", topic, queueId, throwable);
```
Comment (lizhimins) [inline tieredstore/src/main/java/org/apache/rocketmq/tieredstore/core/MessageStoreDispatcherImpl.java:165]: 要不全用 = 保持一下风格一致

**Review by lizhimins — COMMENTED** [review]
You can add some test cases for context

File: tieredstore/src/main/java/org/apache/rocketmq/tieredstore/core/MessageStoreDispatcherImpl.java (hunk 1 above)
Comment (wangshaojie4039) [reply tieredstore/src/main/java/org/apache/rocketmq/tieredstore/core/MessageStoreDispatcherImpl.java:165]: ok

**Review by lizhimins — APPROVED** [review]
