### PR TITLE
[ISSUE #8076] Fix correct min cq offset when delete tiered storage CommitLog

### LINKED ISSUE #8076: [Bug] Fix correct min cq offset when delete tiered storage CommitLog
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).
- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.
- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

Linux

### RocketMQ version

develop branch

### JDK Version

JDK11

### Describe the Bug

We need correct min cq offset when delete tiered storage CommitLog.

### Steps to Reproduce

We need correct min cq offset when delete tiered storage CommitLog.

分级存储 CommitLog 删除时，CommitLog 指向的 cq offset 没有被清理。

### What Did You Expect to See?

CommitLog 指向的 cq offset 需要被清理

### What Did You See Instead?

触发分级存储 CommitLog 删除时，CommitLog 指向的 cq offset 没有被清理

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by lizhimins**
…mmitLog

### Which Issue(s) This PR Fixes

Fixes #8076

### CODE REVIEW

**Review by drpmma — APPROVED** [review]
LGTM

File: tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/FlatCommitLogFile.java [hunk 1]
```diff
@@ -60,4 +60,17 @@ public CompletableFuture<Long> getMinOffsetFromFileAsync() {
                 return firstOffset.get();
             });
     }
+
+    @Override
+    public void destroyExpiredFile(long expireTimestamp) {
+        long beforeOffset = this.getMinOffset();
+        super.destroyExpiredFile(expireTimestamp);
```
Comment (lollipopjin) [inline tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/FlatCommitLogFile.java:67]: Add logs for easier problem troubleshooting
