### PR TITLE
[ISSUE #8997] Ensure there is an opportunity to send a retry message when broker no response

### LINKED ISSUE #8997: [Bug] 一次请求打到坏的broker把超时时间耗光，后两次打到正常的broker也因过期时间为0，无法成功
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

linux and windows

### RocketMQ version

4.7.1 

### JDK Version

jdk11

### Describe the Bug

b2489c47defcd7426ba819008233748

broker-f 突然内存持续上涨，导致服务假死，也未从nameserver摘掉，导致客户端连接超时，虽然mq有三次重试，通过上图发现后两次请求到了正常的broker，应该成功，结果还是失败了

7a5b9cf09a1974768c6bf495e0f801c

### Steps to Reproduce

现在我们无法复现broker内存上涨假死的情况，可以制造一个broker访问不通使得连接把耗时耗光

### What Did You Expect to See?

期望的是，单个请求超时和整体三次重试的超时分开配置

### What Did You See Instead?

期望的是，单个请求超时和整体三次重试的超时分开配置

### Additional Context

无

### PR DESCRIPTION
**Pull request by gaoyf**
… response

### Which Issue(s) This PR Fixes

Fixes #8997

### Brief Description

当broker处于半死不活的状态时（gc，os内存不足等等原因），此时表现无法及时响应客户端的请求。
针对客户端同步发送消息，默认是带有重试策略的。可是此种情况下，客户端可能并没有重试的机会。
详见[分析](https://blog.csdn.net/a417930422/article/details/103489927)。

### How Did You Test This Change?

新增的参数sendMsgMaxTimeoutPerRequest，默认情况下不会影响现有的重试逻辑。
模拟broker暂停的情况，并针对各种情况进行了[测试](https://blog.csdn.net/a417930422/article/details/103489927#test)，情况如下：
image

### CODE REVIEW

**Review by RongtongJin — DISMISSED** [review]
LGTM

**Comment by RongtongJin** [comment]
/home/runner/work/rocketmq/rocketmq/client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java:783:25: 'if' is not followed by whitespace. [WhitespaceAround]

File: client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java [hunk 1]
```diff
@@ -777,8 +777,14 @@ private SendResult sendDefaultImpl(
                             callTimeout = true;
                             break;
                         }
-
-                        sendResult = this.sendKernelImpl(msg, mq, communicationMode, sendCallback, topicPublishInfo, timeout - costTime);
+                        long curTimeout = timeout - costTime;
+                        // In order to prevent the broker from being unresponsive for a long time and thus being unable to retry next time,
+                        // if there is another chance for retry next time, the maximum sending time is modified to the maximum sendMsgMaxTimeoutPerRequest.
+                        if (defaultMQProducer.getSendMsgMaxTimeoutPerRequest() > -1 && times + 1 < timesTotal
```
Comment (lizhimins) [inline client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java:783]: Extracting variables may make the code readable

**Comment by gaoyf** [comment]
@RongtongJin @lizhimins How is the progress of this PR?

**Review by RongtongJin — APPROVED** [review]

**Comment by RongtongJin** [comment]
> @RongtongJin @lizhimins How is the progress of this PR?

LGTM~@lizhimins PTAL~

**Comment by gaoyf** [comment]
@lizhimins

**Review by lizhimins — APPROVED** [review]
