### PR TITLE
[ISSUE #5740] Fix util.getIP sometimes choose localhost over LAN ip.

### LINKED ISSUE #5740: [code discussion] Should the method UtilAll.getIP() return a localhost ?
https://github.com/apache/rocketmq/blob/72786535067310b79138e8ae4509851d85d35b95/common/src/main/java/org/apache/rocketmq/common/UtilAll.java#L604-L619

This method basically traversal network interfaces and find a non-private ip.And if failed to find one, fall back to the whatever ip it found in the first netInterface, which in my setting is localhost(from lo0).
It is used to create unique id, so this is no good behavior right ? 
How about let the lan ip have a higher priority than localhost ?

### PR DESCRIPTION
**Pull request by RagingSpud**
**Make sure set the target branch to `develop`**

## What is the purpose of the change
fix #5740

## Brief changelog
According to RFC 1122, { 127, any } are reserved for internal host loopback address.So `isInternalIP` function return true when ip is between 127.0.0.0~127.255.255.255.
And now it prefers LAN ip to localhost(internal host loopback address).
## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [x] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

File: common/src/main/java/org/apache/rocketmq/common/UtilAll.java [hunk 1]
```diff
@@ -604,7 +606,7 @@ public static byte[] getIP() {
                             if (ipCheck(ipByte)) {
                                 if (!isInternalIP(ipByte)) {
                                     return ipByte;
-                                } else if (internalIP == null) {
+                                } else if (internalIP == null || internalIP[0] == (byte) 127) {
```
Comment (ShadowySpirits) [inline common/src/main/java/org/apache/rocketmq/common/UtilAll.java:609]: This judgment changes the behavior of the getIP function. If we only have lo interface, getIP will throw RuntimeException.

**Review by ShadowySpirits — CHANGES_REQUESTED** [review]

File: common/src/main/java/org/apache/rocketmq/common/UtilAll.java (hunk 1 above)
Comment (RagingSpud) [reply common/src/main/java/org/apache/rocketmq/common/UtilAll.java:609]: If we only have lo interface,`internalIP == null || internalIP[0] == (byte) 127)` will be true，so it will set `internalIP` to localhost and return.
If we have lo and LAN ip，when it find the LAN ip，`internalIP == null || internalIP[0] == (byte) 127)` also will be true, so it will override the value of `internalIP`.
Am I missing something？

Comment (ShadowySpirits) [reply common/src/main/java/org/apache/rocketmq/common/UtilAll.java:609]: You are right. Please ignore this review.

**Review by ShadowySpirits — APPROVED** [review]

**Review by hzh0425 — APPROVED** [review]
LGTM

**Comment by hzh0425** [comment]
Welcome @RagingSpud
