### PR TITLE
[ISSUE #6576] Fix pop lmq message

### LINKED ISSUE #6576: NullPointerException when pop message from light message queue
Pop message from LMQ will return `messageExt` of the original topic.
When building its POP_CK in the client, a NullPointerException will occur in `MQClientAPIImpl#processPopResponse()`.
Because LMQ only has 1 queue, but the original topic has several queues, it will cause an error when getting the original topic's msgQueueOffset from LMQ's msgOffsetInfo.

image
image

client version: 5.1.0

### PR DESCRIPTION
**Pull request by HScarb**
**Make sure set the target branch to `develop`**

## What is the purpose of the change

fix #6576

## Brief changelog

In `MQClientAPIImpl#processPopResponse`, check if popping LMQ message, and construct `sortMap` and `queueIdKey`, `queueOffsetKey`, `index` using LMQ message properties.

## Verifying this change

image

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

File: broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java [hunk 1]
```diff
@@ -643,14 +643,41 @@ private CompletableFuture<Long> popMsgFromQueue(boolean isRetry, GetMessageResul
...
-                    if (!isRetry) {
-                        getMessageResult.addMessage(mapedBuffer);
+                for (SelectMappedBufferResult mappedBuffer : result.getMessageMapedList()) {
+                    if (MixAll.isLmq(topic)) {
+                        List<MessageExt> messageExtList = MessageDecoder.decodesBatch(mappedBuffer.getByteBuffer(),
+                            true, false, true);
+                        mappedBuffer.release();
+                        for (MessageExt messageExt : messageExtList) {
+                            try {
+                                final Long queueOffset = result.getMessageQueueOffset().get(messageExtList.indexOf(messageExt));
```
Comment (cserwen) [inline broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java:653]: Traversing the list with index can save the overhead of indexOf.

File: broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java [hunk 2]
```diff
@@ -643,14 +643,41 @@ private CompletableFuture<Long> popMsgFromQueue(boolean isRetry, GetMessageResul
 
                 atomicRestNum.set(result.getMaxOffset() - result.getNextBeginOffset() + atomicRestNum.get());
                 String brokerName = brokerController.getBrokerConfig().getBrokerName();
-                for (SelectMappedBufferResult mapedBuffer : result.getMessageMapedList()) {
-                    // We should not recode buffer for normal topic message
-                    if (!isRetry) {
-                        getMessageResult.addMessage(mapedBuffer);
+                for (SelectMappedBufferResult mappedBuffer : result.getMessageMapedList()) {
+                    if (MixAll.isLmq(topic)) {
+                        List<MessageExt> messageExtList = MessageDecoder.decodesBatch(mappedBuffer.getByteBuffer(),
```
Comment (pingww) [inline broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java:648]: Parsing the message here will affect the performance. Could you consider compatible processing when the client parses the POP response?

Comment (HScarb) [reply broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java:648]: Indeed. 
I've tried to process it on the client side at first, but we can't get LMQ's queueOffset and queue ID in the client side, because the message was saved with information on the original topic and queue.

Comment (pingww) [reply broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java:648]: LMQ's queueOffset is in properties of message, and queueID is default 0

Comment (vongosling) [reply broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java]: Take another case, if we hope to use the older client to visit our new broker version. Does it enough to modify in the client side?

**Review by pingww — COMMENTED** [review]
Refactoring the code composition here ? I thought it would take so many changes to support lmq’s pop !

File: client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java [hunk 3]
```diff
@@ -1063,73 +1063,124 @@ private PopResult processPopResponse(final String brokerName, final RemotingComm
...
+                    messageExt.getProperties().put(MessageConst.PROPERTY_POP_CK, map.get(key) + MessageConst.KEY_SEPARATOR + messageExt.getQueueOffset());
+                } else {
+                    if (messageExt.getProperty(MessageConst.PROPERTY_POP_CK) == null) {
+                        final String queueIdKey;
+                        final String queueOffsetKey;
+                        final int index;
+                        final Long msgQueueOffset;
+                        if (MixAll.isLmq(topic) && messageExt.getReconsumeTimes() == 0 && StringUtils.isNotEmpty(
+                            messageExt.getProperty(MessageConst.PROPERTY_INNER_MULTI_DISPATCH))) {
+                            // process LMQ, LMQ topic has only 1 queue, which queue id is 0
```
Comment (pingww) [inline client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java:1103]: Should we define this queue id 0 as a constant ？

**Review by pingww — DISMISSED** [review]

File: client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java (hunk 3 above)
Comment (HScarb) [reply client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java:1103]: OK

**Review by pingww — APPROVED** [review]
