### PR TITLE
[ISSUE #7013]polish ColdDataCheckService's logic

### LINKED ISSUE #7013: [Enhancement] The logic of coldDataCheckService() needs to be optimized
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

Mac, M1

### RocketMQ version

latest

### JDK Version

_No response_

### Describe the Bug

Regardless of whether the cold read control switch is turned on, initPageSize() will be executed. However in some cases it may trigger an error.

### Steps to Reproduce

turn off the related switch: 
coldDataScanEnable                                =  false
coldDataFlowControlEnable                    =  false

then start the broker, there will still be such log in store.log: 
2023-07-03 13:54:01 INFO main - initPageSize pageSize: 4096

However, this discussion shows that in some cases, it will lead to an error:
https://github.com/apache/rocketmq/discussions/7007

### What Did You Expect to See?

The initialization should only be triggered after the switch is turned on.

### What Did You See Instead?

then start the broker, there is such log in store.log: 
2023-07-03 13:54:01 INFO main - initPageSize pageSize: 4096

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by GenerousMan**
### Which Issue(s) This PR Fixes

Fixes #7013

### CODE REVIEW

File: store/src/main/java/org/apache/rocketmq/store/CommitLog.java [hunk 1]
```diff
@@ -2089,6 +2089,16 @@ public void run() {
...
                         this.waitForRunning(defaultMessageStore.getMessageStoreConfig().getTimerColdDataCheckIntervalMs());
                     }
+
+                    if (pageSize < 0) {
+                        try {
+                            initPageSize();
+                        } catch (Exception e) {
+                            log.error("Before scanning files in pagecache, initing has failed.", e);
+                            return;
+                        }
```
Comment (RongtongJin) [inline store/src/main/java/org/apache/rocketmq/store/CommitLog.java:2099]: 这里无法抓住java.lang.UnsatisfiedLinkError

**Review by RongtongJin — APPROVED** [review]
