### PR TITLE
[ISSUE #9217] Fix broker's inflight and available message counts incorrect when the pop consumer service is enabled

### LINKED ISSUE #9217: [Bug] Broker's inflight and available message counts are incorrect when the pop consumer service is enabled
### Before Creating the Bug Report

- [x] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [x] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [x] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

Linux 5.10

### RocketMQ version

develop branch | before 5.3.2-SNAPSHOT

### JDK Version

JDK11

### Describe the Bug

Broker inflight and available messsage count wrong when pop consumer service enable

### Steps to Reproduce

Enable the pop kv feature

Image

### What Did You Expect to See?

Image

### What Did You See Instead?

inflight and available messsage count wrong

### Additional Context

inflight and available messsage count wrong

### PR DESCRIPTION
**Pull request by lizhimins**
### Which Issue(s) This PR Fixes

Fixes #9217

### CODE REVIEW

File: broker/src/main/java/org/apache/rocketmq/broker/metrics/ConsumerLagCalculator.java [hunk 1]
```diff
@@ -456,14 +456,11 @@ public long getAvailableMsgCount(String group, String topic, int queueId, boolea
         }
 
         long pullOffset;
-        if (isPop) {
+        if (isPop && !brokerConfig.isPopConsumerKVServiceEnable()) {
             pullOffset = popBufferMergeService.getLatestOffset(topic, group, queueId);
             if (pullOffset < 0) {
                 pullOffset = offsetManager.queryOffset(group, topic, queueId);
             }
-            if (pullOffset < 0) {
```
Comment (lizhimins) [inline broker/src/main/java/org/apache/rocketmq/broker/metrics/ConsumerLagCalculator.java:464]: There is another duplicate judgment

**Review by qianye1001 — APPROVED** [review]
LGTM

**Review by lollipopjin — APPROVED** [review]
LGTM
