### PR TITLE
[ISSUE #7822] fix NettyRemotingClient can't connect to IPv6 address.

### LINKED ISSUE #7822: [Bug] NettyRemotingClient can't connect to IPv6 address.
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

CentOS7

### RocketMQ version

5.1.5

### JDK Version

jdk8

### Describe the Bug

The getHostAndPort method is not supported for IPv6 address.

### Steps to Reproduce

1. enbale IPv6 for RocketMQ;
2. use DefaultPushConsumer.

### What Did You Expect to See?

No exceptions are thrown.

### What Did You See Instead?

RemotingConnectException is thrown.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by kingkh1995**
### Which Issue(s) This PR Fixes

Fixes #7822 

### Brief Description

update getHostAndPort method in NettyRemotingClient.

### How Did You Test This Change?

code covered

### CODE REVIEW

**Review by RongtongJin — APPROVED** [review]

File: remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java [hunk 1]
```diff
@@ -351,9 +351,10 @@ public void initChannel(SocketChannel ch) {
         return bootstrap;
     }
 
-    // Do not use RemotingUtil, it will directly resolve the domain
+    // Do not use RemotingHelper.string2SocketAddress(), it will directly resolve the domain
     private String[] getHostAndPort(String address) {
-        return address.split(":");
+        int split = address.lastIndexOf(":");
+        return split < 0 ? new String[]{address} : new String[]{address.substring(0, split), address.substring(split + 1)};
     }
```
Comment (RongtongJin) [inline remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java:358]: It would be better to add an UT.

**Comment by leizhiyuan** [comment]
which ipv6 address？

**Review by yuz10 — APPROVED** [review]
