### PR TITLE
[ISSUE #5838] retry to send when broker returns SYSTEM_BUSY

### LINKED ISSUE #5838: Client will not retry to send message when broker busy
**BUG REPORT**

1. Please describe the issue you observed:

Client will retry when server returns the following code:
image

But some code of broker-busy is `SYSTEM_BUSY`, the client will stop to retry. Broker's glitch will cause the client to stop retrying, resulting in sending failure. If it can retry to other Broker nodes, this problem can be avoided.

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

### PR DESCRIPTION
**Pull request by cserwen**
**Make sure set the target branch to `develop`**

## What is the purpose of the change

fix #5838 

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

File: client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java [hunk 1]
```diff
@@ -72,7 +72,8 @@ public class DefaultMQProducer extends ClientConfig implements MQProducer {
         ResponseCode.SYSTEM_ERROR,
         ResponseCode.NO_PERMISSION,
         ResponseCode.NO_BUYER_ID,
-        ResponseCode.NOT_IN_CURRENT_UNIT
+        ResponseCode.NOT_IN_CURRENT_UNIT,
+        ResponseCode.SYSTEM_BUSY
```
Comment (ShadowySpirits) [inline client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java:76]: How about removing TOPIC_NOT_EXIST?

**Review by ShadowySpirits — CHANGES_REQUESTED** [review]

File: client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java (hunk 1 above)
Comment (cserwen) [reply client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java:76]: We don't know the intent of the author who wrote it, so removing it is probably not a good option. Although I also think that client should not retry when broker returns `TOPIC_NOT_EXIST`:smile:. @ShadowySpirits

Comment (Oliverwqcwrw) [reply client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java:76]: @wz2cool  WDYT? :-)

**Comment by lizhimins** [comment]
System busy means server is overload, why we need retry send message?

File: client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java (hunk 1 above)
Comment (lizhimins) [reply client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java:76]: System busy means server is overload, why we need retry send message?

Comment (humkum) [reply client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java:76]: > System busy means server is overload, why we need retry send message?

To make sure message which send failed can retry to send success to another brokers.

**Comment by cserwen** [comment]
> System busy means server is overload, why we need retry send message?

@lizhimins refer to #5845

**Comment by wz2cool** [comment]
we have lot of disussion about it,  plz see #2542 ,  I think you can add SYSTEM_BUSY by addRetryResponseCode by yourself  
image

File: client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java (hunk 1 above)
Comment (wz2cool) [reply client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java:76]: we have  some disussion about it  plz see #2726

**Comment by wz2cool** [comment]
> > @cserwen
> > we have lot of disussion about it, plz see #2726 , I think you can add SYSTEM_BUSY using addRetryResponseCode method by yourself . you can see my changes #2729
> > image
> 
> @wz2cool The sdk's built-in retry is necessary. System busy is a very common situation. If this situation needs to be specified by the user, then our sdk seems difficult to use. In addition, we can easily implement it, why require users to add code by themselves

some rocketmq designers/contributors worried about overload, so sdk's build-in retry PR can't be merged long time ago. I think it's ok to use sdk's built in retry if there is not any risk to do this.

**Comment by cserwen** [comment]
> > > @cserwen
> > > we have lot of disussion about it, plz see #2726 , I think you can add SYSTEM_BUSY using addRetryResponseCode method by yourself . you can see my changes #2729
> > > image
> > 
> > 
> > @wz2cool The sdk's built-in retry is necessary. System busy is a very common situation. If this situation needs to be specified by the user, then our sdk seems difficult to use. In addition, we can easily implement it, why require users to add code by themselves
> 
> some rocketmq designers/members/contributors worried about overload, so sdk's build-in retry PR can't be merged long time ago. I think it's ok to use sdk's built in retry if there is no any risk to do this.

Actually，sdk will also retry when broker returns SYSTEM_ERROR. And when the pagecache is busy, the response code is SYSTEM_ERROR. In our internal, RocketMQ has been running for more than two years, and the entire cluster has not been overloaded because of a single Broker's busy, so this worry is unnecessary. Besides, the commercial version also supports retrying in this case, why can't the open-source version support it?

**Comment by wz2cool** [comment]
> > > > @cserwen
> > > > we have lot of disussion about it, plz see #2726 , I think you can add SYSTEM_BUSY using addRetryResponseCode method by yourself . you can see my changes #2729
> > > > image
> > > 
> > > 
> > > @wz2cool The sdk's built-in retry is necessary. System busy is a very common situation. If this situation needs to be specified by the user, then our sdk seems difficult to use. In addition, we can easily implement it, why require users to add code by themselves
> > 
> > 
> > some rocketmq designers/members/contributors worried about overload, so sdk's build-in retry PR can't be merged long time ago. I think it's ok to use sdk's built in retry if there is no any risk to do this.
> 
> Actually，sdk will also retry when broker returns SYSTEM_ERROR. And when the pagecache is busy, the response code is SYSTEM_ERROR. In our internal, RocketMQ has been running for more than two years, and the entire cluster has not been overloaded because of a single Broker's busy, so this worry is unnecessary. Besides, the commercial version also supports retrying in this case, why can't the open-source version support it?

In some cases, users don't run multi rocketmqs as cluster , they just run one rocketmq/nameserver (considering the cost) ,  I think commercial version  is also a cluster.
I support to use build-in retrying if no risk in any case. Could someone make some tests to prove it. 
Currently, I think config is a good choose.

**Review by yuz10 — APPROVED** [review]

**Review by yuz10 — APPROVED** [review]

File: client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java (hunk 1 above)
Comment (cserwen) [reply client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java]: > How about removing TOPIC_NOT_EXIST?
 
Sometimes a topic will be deleted or disabled on a broker node. Maybe due to the failed routing update, it may request this broker, so retrying here is still necessary. @ShadowySpirits

**Review by Oliverwqcwrw — APPROVED** [review]

**Review by wz2cool — COMMENTED** [review]
looks good

**Comment by zhbdesign** [comment]
A busy exception occurred while sending the message, and the exception information is as follows: com.alibaba.rocketmq.client.exception.MQBrokerException: CODE: 2  DESC: [TIMEOUT_CLEAN_QUEUE]broker busy, start flow control for a while, period in queue: 208ms, size of queue: 8， Without any retry attempts, the client is configured by default. Sometimes this exception occurs and the message is sent out, but I cannot get the sendresult result. Is this a normal phenomenon? I see that the code usually does not send the message successfully when this exception occurs. My version has not yet added SYSTEM_BUSY to automatic retry
