### PR TITLE
[ISSUE #8405] Add the ability to write ConsumeQueue using fileChannel to prevent JVM crashes in some situations

### LINKED ISSUE #8405: [Bug] Deleting ConsumeQueue files may cause JVM crashes
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

All platform

### RocketMQ version

4.9.3 ～ lastest, after #3657

### JDK Version

All versions

### Describe the Bug

When topics are created and deleted frequently, a JVM crash occurred. Analysis revealed that when a topic is deleted, the file is unmapped. During this time, the ReputMessageService dispatches the consumeQueue and writes to the mmap file, which may cause the JVM to crash.

### Steps to Reproduce

Start the broker
Start the producer to send continuously
While sending, use the admin to delete the topic
Finally, the broker crashes, and the exception stack trace is consistent with the one online
image
image

### What Did You Expect to See?

No JVM crash

### What Did You See Instead?

JVM crash

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by RongtongJin**
### Which Issue(s) This PR Fixes

Fixes #8405

### Brief Description

Add the ability to write ConsumeQueue using fileChannel to prevent JVM crashes in some situations

### CODE REVIEW

**Review by humkum — APPROVED** [review]

**Review by fuyou001 — APPROVED** [review]
LGMT

**Comment by humkum** [comment]
Excuse me. How can this prevent JVM crashes? Is it because fileChannel uses off-heap memory?

File: store/src/main/java/org/apache/rocketmq/store/ConsumeQueue.java [hunk 1]
```diff
@@ -833,7 +833,13 @@ private boolean putMessagePositionInfo(final long offset, final int size, final
                 }
             }
             this.setMaxPhysicOffset(offset + size);
-            return mappedFile.appendMessage(this.byteBufferIndex.array());
+            boolean appendResult;
+            if (messageStore.getMessageStoreConfig().isPutConsumeQueueDataByFileChannel()) {
+                appendResult = mappedFile.appendMessageUsingFileChannel(this.byteBufferIndex.array());
```
Comment (caigy) [inline store/src/main/java/org/apache/rocketmq/store/ConsumeQueue.java:838]: `byteBufferIndex`, of which type is `ByteBuffer`, is transformed to `byte[]` and then transformed back into `ByteBuffer` in `DefaultMappedFile.appendMessageUsingFileChannel()`. IMO it's unnecessary.

**Review by caigy — CHANGES_REQUESTED** [review]

**Comment by RongtongJin** [comment]
> How can this prevent JVM crashes? Is it because fileChannel uses off-heap memory?

yes

**Review by caigy — APPROVED** [review]
