### PR TITLE
[ISSUE 1491] Ignore IllegalStateException when remove shutdown hook

### LINKED ISSUE #1491: RocketMQ spring will throw IllegalStateException when the spring application is closed
**BUG REPORT**

1. Please describe the issue you observed:
RocketMQ spring will throw IllegalStateException when the spring application is closed
refer [rocketmq-spring issue136](https://github.com/apache/rocketmq-spring/issues/136).
2. Please tell us about your environment:
Mac OS
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
When producer invoke shutdown, shutdownhook of AsyncTraceDispatcher is removed.
In RocketMQ spring, shutdown method of producer is invoked when the application is closed. While JVM is closing, and shutdown hook is removed at the same time, which causes IllegalStateException to be thrown.

### PR DESCRIPTION
**Pull request by RongtongJin**
## What is the purpose of the change
fix #1491
If shutdown of the JVM in progress already, we don't need to remove the hook, just ignore the IllegalStateException.

## Brief changelog

Ignore IllegalStateException when remove shutdown hook

## Verifying this change

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

File: client/src/main/java/org/apache/rocketmq/client/trace/AsyncTraceDispatcher.java [hunk 1]
```diff
@@ -216,7 +216,11 @@ public void run() {
 
     public void removeShutdownHook() {
         if (shutDownHook != null) {
-            Runtime.getRuntime().removeShutdownHook(shutDownHook);
+            try {
+                Runtime.getRuntime().removeShutdownHook(shutDownHook);
+            } catch (IllegalStateException e) {
+                // ignore - VM is already shutting down
```
Comment (vongosling) [inline client/src/main/java/org/apache/rocketmq/client/trace/AsyncTraceDispatcher.java]: Do we really want to get rid of ShutdownHook？
