### PR TITLE
[ISSUE #7710] Handle blank string for UtilAll#split to fix the bugs of ACL

### LINKED ISSUE #7710: [Bug] Deleting the last item problem of the ACL topic/group perms or the global white list caused by the UtilAll#split func flaw
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

OS(CentOS release 7.6.1810)

### RocketMQ version

branch(develop) version(5.1.5-SNAPSHOT)

### JDK Version

Compliler(Oracke JDK 1.8.0_361) OS(CentOS release 7.6.1810)

### Describe the Bug

I found an bug of ACL during my work on RocketMQ.
When I tried to delete the last item of the ACL topic/group perms, there was an error which indicates the resouce fomat is incrorrect. And there's also an similar problem of the global white list, which is always remain an empty data at last.

### Steps to Reproduce

**To reproduce you can use two ways:**
1. If you use the Dashboard(take the topic/group perms for example)
1.1 Create an ACL with mutiple topic perms and group perms.
1.2 Delete the topic perms or group perms one by one.
1.3 The error woud appear when delete the last one.

AgAACF5zlnReY1XDkERMf6P-SgV5fqC1
AgAACF5zlnR_G2hISrFGkp9IHvbLVnhw
AgAACF5zlnQIxRfBwMZA4odWFJ1KCjd_

2. If you want to create an test method for reproduce
2.1 New an DefaultMQAdminExt and config it with namesrv and then start it.
2.2 New an PlainAccessConfig and setGroupPerms(Collections.EMPTY_LIST), setTopicPerms(Collections.EMPTY_LIST).
2.3 Then call DefaultMQAdminExt #createAndUpdatePlainAccessConfig.
2.4 Or to call DefaultMQAdminExt #updateGlobalWhiteAddrConfig with the second parmeter an empty string.

图片
图片

### What Did You Expect to See?

For the topic/group perms, it should not be an error to delete the last item.
图片

For the global white list, it should not be an empty data

图片

### What Did You See Instead?

For the topic/group perms, it popup an error: 
org.apache.rocketmq.client.exception.MQClientException: CODE: 209  DESC: Parse Resource format error for .
The expected resource format is 'Res=Perm'. For example: topicA=SUB

AgAACF5zlnReY1XDkERMf6P-SgV5fqC1

For the global white list, it remains an empty data

AgAACF5zlnR_G2hISrFGkp9IHvbLVnhw

### Additional Context

**I've already found and fixed the bug, and I'll submit an PR later.**

### PR DESCRIPTION
**Pull request by Qinglong-Lee**
### Which Issue(s) This PR Fixes

Fixes #7710

### Brief Description

The PR is for a bug the ACL, which caused the problem of deleting the last item of the topic/group perms or the global white list.
The bug is due to the flaw of UtilAll#split func which didn't handle the blank string case properly.
So I've fixed it.
### How Did You Test This Change?

This change have been tested by unit test and the bug have been tested on local.
I've also searched the usages of the changed method globally.
I'm sure the bug has been fixed and has no influence on any other functions of the project.

图片
图片

### CODE REVIEW

**Comment by Qinglong-Lee** [comment]
@RongtongJin @fuyou001

File: common/src/main/java/org/apache/rocketmq/common/UtilAll.java [hunk 1]
```diff
@@ -31,13 +31,7 @@
...
 import java.text.ParseException;
 import java.text.SimpleDateFormat;
-import java.util.Arrays;
-import java.util.Calendar;
-import java.util.Date;
-import java.util.Enumeration;
-import java.util.Iterator;
-import java.util.List;
-import java.util.Map;
+import java.util.*;
```
Comment (RongtongJin) [inline common/src/main/java/org/apache/rocketmq/common/UtilAll.java:34]: Using the '.*' form of import should be avoided

Comment (Qinglong-Lee) [reply common/src/main/java/org/apache/rocketmq/common/UtilAll.java]: Hi，RongtongJin, I've fixed the import issue, please review again, thanks.

Comment (Qinglong-Lee) [reply common/src/main/java/org/apache/rocketmq/common/UtilAll.java]: Btw, why can't I find the method org.apache.rocketmq.tools.admin.DefaultMQAdminExt#examineBrokerClusterAclConfig in the latest version? Does it migrated to other name?

**Review by RongtongJin — APPROVED** [review]
