### PR TITLE
[ISSUE #6373] Optimized log printing and fixed null pointer exceptions

### LINKED ISSUE #6373: Optimized log printing and fixed null pointer exceptions
1. Print out the path of the configuration file during startup. If the path of the configuration file is incorrect, it is convenient for troubleshooting
2. Fixed a null pointer exception when namesrvAddr was not configured
3. Prints all stack information for the exception at startup

### PR DESCRIPTION
**Pull request by socutes**
close #6373

### CODE REVIEW

**Comment by socutes** [comment]
@xdkxlk PTAL

File: proxy/src/main/java/org/apache/rocketmq/proxy/service/mqclient/MQClientAPIFactory.java [hunk 1]
```diff
@@ -55,6 +55,9 @@ protected void init() {
         System.setProperty(ClientConfig.SEND_MESSAGE_WITH_VIP_CHANNEL_PROPERTY, "false");
         ProxyConfig proxyConfig = ConfigurationManager.getProxyConfig();
         if (StringUtils.isEmpty(proxyConfig.getNamesrvDomain())) {
+            if (proxyConfig.getNamesrvAddr() == null || proxyConfig.getNamesrvAddr().isEmpty()) {
```
Comment (zhouxinyu) [inline proxy/src/main/java/org/apache/rocketmq/proxy/service/mqclient/MQClientAPIFactory.java:58]: Try [isNullOrEmpty](https://guava.dev/releases/23.0/api/docs/com/google/common/base/Strings.html#isNullOrEmpty-java.lang.String-) to simplify this line.

**Review by xdkxlk — APPROVED** [review]
