### PR TITLE
[ISSUE #7381] Fix the problem of inaccurate timer message metric

### LINKED ISSUE #7381: [Bug] The metrics of timerMessage are inaccurate and may even be negative.
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

macos

### RocketMQ version

5.1.3

### JDK Version

_No response_

### Describe the Bug

After the timer message is enqueueed, if the entry time wheel is slow, it will be directly thrown into the dequePutQueue, and the increment operation of metrics will not be performed.
This will cause the metrics of timerMessage to be inaccurate and may even be negative.

### Steps to Reproduce

just start a local broker, and send timerMessage into it.
you need to set the deliver time now + 3~5ms.

### What Did You Expect to See?

metrics should be the num of timer messages in the timing wheel.

### What Did You See Instead?

image

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by GenerousMan**
### Which Issue(s) This PR Fixes

Fixes #7381

### Brief Description

When entering the time wheel, if it is judged that it can be dequeued, its enqueue time is set to infinity, which means that it has never entered the time wheel.

Skip messages with an infinite enqueue time when counting metrics.

### CODE REVIEW

File: store/src/main/java/org/apache/rocketmq/store/timer/TimerMessageStore.java [hunk 1]
```diff
@@ -599,7 +599,12 @@ public void addMetric(MessageExt msg, int value) {
             if (null == msg || null == msg.getProperty(MessageConst.PROPERTY_REAL_TOPIC)) {
                 return;
             }
-            timerMetrics.addAndGet(msg.getProperty(MessageConst.PROPERTY_REAL_TOPIC), value);
+            if (msg.getProperty(TIMER_ENQUEUE_MS) != null
```
Comment (joeCarf) [inline store/src/main/java/org/apache/rocketmq/store/timer/TimerMessageStore.java:602]: NumberUtils.toLong() might be more clear

File: store/src/main/java/org/apache/rocketmq/store/timer/TimerMessageStore.java [hunk 2]
```diff
@@ -1452,9 +1458,14 @@ public void run() {
...
                             try {
                                 perfCounterTicks.startTick(DEQUEUE_PUT);
-                                DefaultStoreMetricsManager.incTimerDequeueCount(getRealTopic(tr.getMsg()));
-                                addMetric(tr.getMsg(), -1);
-                                MessageExtBrokerInner msg = convert(tr.getMsg(), tr.getEnqueueTime(), needRoll(tr.getMagic()));
+                                MessageExt msgExt = tr.getMsg();
+                                DefaultStoreMetricsManager.incTimerDequeueCount(getRealTopic(msgExt));
+                                if (tr.getEnqueueTime() == Long.MAX_VALUE) {
+                                    // never enqueue, mark it.
+                                    MessageAccessor.putProperty(msgExt, TIMER_ENQUEUE_MS, Long.MAX_VALUE+"");
```
Comment (joeCarf) [inline store/src/main/java/org/apache/rocketmq/store/timer/TimerMessageStore.java:1465]: will `String.valueOF(Long.MAX_VALUE)` be more clear?

File: store/src/main/java/org/apache/rocketmq/store/timer/TimerMessageStore.java (hunk 1 above)
Comment (GenerousMan) [reply store/src/main/java/org/apache/rocketmq/store/timer/TimerMessageStore.java:603]: done

File: store/src/main/java/org/apache/rocketmq/store/timer/TimerMessageStore.java (hunk 2 above)
Comment (GenerousMan) [reply store/src/main/java/org/apache/rocketmq/store/timer/TimerMessageStore.java]: done

**Review by RongtongJin — APPROVED** [review]

File: store/src/main/java/org/apache/rocketmq/store/timer/TimerMessageStore.java (hunk 1 above)
Comment (joeCarf) [reply store/src/main/java/org/apache/rocketmq/store/timer/TimerMessageStore.java:603]: no need of `msg.getProperty(TIMER_ENQUEUE_MS) != null` if using `NumberUtils.toLong`, you can check this out

**Review by mxsm — APPROVED** [review]
LGTM

File: store/src/main/java/org/apache/rocketmq/store/timer/TimerMessageStore.java (hunk 1 above)
Comment (GenerousMan) [reply store/src/main/java/org/apache/rocketmq/store/timer/TimerMessageStore.java:603]: Under normal situation, this indicator is still null when exiting the queue, so this judgment is necessary.
When leaving the queue, the 'enququ_time' attribute in the message has not been retrieved from the timerRequest yet. When leaving the queue, this attribute will not be null unless it is determined that it has never entered the time wheel.
